name: Test
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    env:
      SKIP_ENV_VALIDATION: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run npm install
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Run formatter
        run: npm run format

      - name: Run tsc
        run: npm run check

      - name: Run unit tests & coverage
        run: npm run test:cov

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: jarvis2f/vortex
